
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
  TENANT: 'TENANT',
  AGENT: 'AGENT',
  ARTISAN: 'ARTISAN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const VerificationStatus = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
} as const

export type VerificationStatus = (typeof VerificationStatus)[keyof typeof VerificationStatus]


export const SignatureStatus = {
  PENDING: 'PENDING',
  SIGNED_TENANT: 'SIGNED_TENANT',
  SIGNED_OWNER: 'SIGNED_OWNER',
  COMPLETED: 'COMPLETED'
} as const

export type SignatureStatus = (typeof SignatureStatus)[keyof typeof SignatureStatus]


export const PropertyType = {
  APPARTEMENT: 'APPARTEMENT',
  VILLA: 'VILLA',
  STUDIO: 'STUDIO',
  MAGASIN: 'MAGASIN',
  BUREAU: 'BUREAU',
  TERRAIN: 'TERRAIN'
} as const

export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType]


export const LeaseStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  TERMINATED: 'TERMINATED',
  CANCELLED: 'CANCELLED'
} as const

export type LeaseStatus = (typeof LeaseStatus)[keyof typeof LeaseStatus]


export const PaymentType = {
  LOYER: 'LOYER',
  DEPOSIT: 'DEPOSIT',
  CHARGES: 'CHARGES',
  FEE: 'FEE'
} as const

export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType]


export const PaymentStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const IncidentStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  QUOTATION: 'QUOTATION',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
} as const

export type IncidentStatus = (typeof IncidentStatus)[keyof typeof IncidentStatus]


export const MissionStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type MissionStatus = (typeof MissionStatus)[keyof typeof MissionStatus]


export const MissionType = {
  VISITE: 'VISITE',
  ETAT_DES_LIEUX_ENTREE: 'ETAT_DES_LIEUX_ENTREE',
  ETAT_DES_LIEUX_SORTIE: 'ETAT_DES_LIEUX_SORTIE',
  PHOTOS: 'PHOTOS'
} as const

export type MissionType = (typeof MissionType)[keyof typeof MissionType]
