
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Mission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Mission
 * 
 */
export type MissionModel = runtime.Types.Result.DefaultSelection<Prisma.$MissionPayload>

export type AggregateMission = {
  _count: MissionCountAggregateOutputType | null
  _avg: MissionAvgAggregateOutputType | null
  _sum: MissionSumAggregateOutputType | null
  _min: MissionMinAggregateOutputType | null
  _max: MissionMaxAggregateOutputType | null
}

export type MissionAvgAggregateOutputType = {
  fee: number | null
}

export type MissionSumAggregateOutputType = {
  fee: number | null
}

export type MissionMinAggregateOutputType = {
  id: string | null
  type: $Enums.MissionType | null
  status: $Enums.MissionStatus | null
  fee: number | null
  dateScheduled: Date | null
  reportData: string | null
  createdAt: Date | null
  propertyId: string | null
  agentId: string | null
}

export type MissionMaxAggregateOutputType = {
  id: string | null
  type: $Enums.MissionType | null
  status: $Enums.MissionStatus | null
  fee: number | null
  dateScheduled: Date | null
  reportData: string | null
  createdAt: Date | null
  propertyId: string | null
  agentId: string | null
}

export type MissionCountAggregateOutputType = {
  id: number
  type: number
  status: number
  fee: number
  dateScheduled: number
  reportData: number
  createdAt: number
  propertyId: number
  agentId: number
  _all: number
}


export type MissionAvgAggregateInputType = {
  fee?: true
}

export type MissionSumAggregateInputType = {
  fee?: true
}

export type MissionMinAggregateInputType = {
  id?: true
  type?: true
  status?: true
  fee?: true
  dateScheduled?: true
  reportData?: true
  createdAt?: true
  propertyId?: true
  agentId?: true
}

export type MissionMaxAggregateInputType = {
  id?: true
  type?: true
  status?: true
  fee?: true
  dateScheduled?: true
  reportData?: true
  createdAt?: true
  propertyId?: true
  agentId?: true
}

export type MissionCountAggregateInputType = {
  id?: true
  type?: true
  status?: true
  fee?: true
  dateScheduled?: true
  reportData?: true
  createdAt?: true
  propertyId?: true
  agentId?: true
  _all?: true
}

export type MissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Mission to aggregate.
   */
  where?: Prisma.MissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Missions to fetch.
   */
  orderBy?: Prisma.MissionOrderByWithRelationInput | Prisma.MissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Missions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Missions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Missions
  **/
  _count?: true | MissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MissionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MissionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MissionMaxAggregateInputType
}

export type GetMissionAggregateType<T extends MissionAggregateArgs> = {
      [P in keyof T & keyof AggregateMission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMission[P]>
    : Prisma.GetScalarType<T[P], AggregateMission[P]>
}




export type MissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MissionWhereInput
  orderBy?: Prisma.MissionOrderByWithAggregationInput | Prisma.MissionOrderByWithAggregationInput[]
  by: Prisma.MissionScalarFieldEnum[] | Prisma.MissionScalarFieldEnum
  having?: Prisma.MissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MissionCountAggregateInputType | true
  _avg?: MissionAvgAggregateInputType
  _sum?: MissionSumAggregateInputType
  _min?: MissionMinAggregateInputType
  _max?: MissionMaxAggregateInputType
}

export type MissionGroupByOutputType = {
  id: string
  type: $Enums.MissionType
  status: $Enums.MissionStatus
  fee: number
  dateScheduled: Date | null
  reportData: string | null
  createdAt: Date
  propertyId: string
  agentId: string | null
  _count: MissionCountAggregateOutputType | null
  _avg: MissionAvgAggregateOutputType | null
  _sum: MissionSumAggregateOutputType | null
  _min: MissionMinAggregateOutputType | null
  _max: MissionMaxAggregateOutputType | null
}

type GetMissionGroupByPayload<T extends MissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MissionGroupByOutputType[P]>
      }
    >
  >



export type MissionWhereInput = {
  AND?: Prisma.MissionWhereInput | Prisma.MissionWhereInput[]
  OR?: Prisma.MissionWhereInput[]
  NOT?: Prisma.MissionWhereInput | Prisma.MissionWhereInput[]
  id?: Prisma.StringFilter<"Mission"> | string
  type?: Prisma.EnumMissionTypeFilter<"Mission"> | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFilter<"Mission"> | $Enums.MissionStatus
  fee?: Prisma.IntFilter<"Mission"> | number
  dateScheduled?: Prisma.DateTimeNullableFilter<"Mission"> | Date | string | null
  reportData?: Prisma.StringNullableFilter<"Mission"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Mission"> | Date | string
  propertyId?: Prisma.StringFilter<"Mission"> | string
  agentId?: Prisma.StringNullableFilter<"Mission"> | string | null
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  agent?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type MissionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  dateScheduled?: Prisma.SortOrderInput | Prisma.SortOrder
  reportData?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  agentId?: Prisma.SortOrderInput | Prisma.SortOrder
  property?: Prisma.PropertyOrderByWithRelationInput
  agent?: Prisma.UserOrderByWithRelationInput
}

export type MissionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MissionWhereInput | Prisma.MissionWhereInput[]
  OR?: Prisma.MissionWhereInput[]
  NOT?: Prisma.MissionWhereInput | Prisma.MissionWhereInput[]
  type?: Prisma.EnumMissionTypeFilter<"Mission"> | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFilter<"Mission"> | $Enums.MissionStatus
  fee?: Prisma.IntFilter<"Mission"> | number
  dateScheduled?: Prisma.DateTimeNullableFilter<"Mission"> | Date | string | null
  reportData?: Prisma.StringNullableFilter<"Mission"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Mission"> | Date | string
  propertyId?: Prisma.StringFilter<"Mission"> | string
  agentId?: Prisma.StringNullableFilter<"Mission"> | string | null
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  agent?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type MissionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  dateScheduled?: Prisma.SortOrderInput | Prisma.SortOrder
  reportData?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  agentId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MissionCountOrderByAggregateInput
  _avg?: Prisma.MissionAvgOrderByAggregateInput
  _max?: Prisma.MissionMaxOrderByAggregateInput
  _min?: Prisma.MissionMinOrderByAggregateInput
  _sum?: Prisma.MissionSumOrderByAggregateInput
}

export type MissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.MissionScalarWhereWithAggregatesInput | Prisma.MissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.MissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MissionScalarWhereWithAggregatesInput | Prisma.MissionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Mission"> | string
  type?: Prisma.EnumMissionTypeWithAggregatesFilter<"Mission"> | $Enums.MissionType
  status?: Prisma.EnumMissionStatusWithAggregatesFilter<"Mission"> | $Enums.MissionStatus
  fee?: Prisma.IntWithAggregatesFilter<"Mission"> | number
  dateScheduled?: Prisma.DateTimeNullableWithAggregatesFilter<"Mission"> | Date | string | null
  reportData?: Prisma.StringNullableWithAggregatesFilter<"Mission"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Mission"> | Date | string
  propertyId?: Prisma.StringWithAggregatesFilter<"Mission"> | string
  agentId?: Prisma.StringNullableWithAggregatesFilter<"Mission"> | string | null
}

export type MissionCreateInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutMissionsInput
  agent?: Prisma.UserCreateNestedOneWithoutMissionsAcceptedInput
}

export type MissionUncheckedCreateInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  propertyId: string
  agentId?: string | null
}

export type MissionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutMissionsNestedInput
  agent?: Prisma.UserUpdateOneWithoutMissionsAcceptedNestedInput
}

export type MissionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  agentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MissionCreateManyInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  propertyId: string
  agentId?: string | null
}

export type MissionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MissionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  agentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MissionListRelationFilter = {
  every?: Prisma.MissionWhereInput
  some?: Prisma.MissionWhereInput
  none?: Prisma.MissionWhereInput
}

export type MissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MissionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  dateScheduled?: Prisma.SortOrder
  reportData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
}

export type MissionAvgOrderByAggregateInput = {
  fee?: Prisma.SortOrder
}

export type MissionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  dateScheduled?: Prisma.SortOrder
  reportData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
}

export type MissionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  dateScheduled?: Prisma.SortOrder
  reportData?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
}

export type MissionSumOrderByAggregateInput = {
  fee?: Prisma.SortOrder
}

export type MissionCreateNestedManyWithoutAgentInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutAgentInput, Prisma.MissionUncheckedCreateWithoutAgentInput> | Prisma.MissionCreateWithoutAgentInput[] | Prisma.MissionUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutAgentInput | Prisma.MissionCreateOrConnectWithoutAgentInput[]
  createMany?: Prisma.MissionCreateManyAgentInputEnvelope
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
}

export type MissionUncheckedCreateNestedManyWithoutAgentInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutAgentInput, Prisma.MissionUncheckedCreateWithoutAgentInput> | Prisma.MissionCreateWithoutAgentInput[] | Prisma.MissionUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutAgentInput | Prisma.MissionCreateOrConnectWithoutAgentInput[]
  createMany?: Prisma.MissionCreateManyAgentInputEnvelope
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
}

export type MissionUpdateManyWithoutAgentNestedInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutAgentInput, Prisma.MissionUncheckedCreateWithoutAgentInput> | Prisma.MissionCreateWithoutAgentInput[] | Prisma.MissionUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutAgentInput | Prisma.MissionCreateOrConnectWithoutAgentInput[]
  upsert?: Prisma.MissionUpsertWithWhereUniqueWithoutAgentInput | Prisma.MissionUpsertWithWhereUniqueWithoutAgentInput[]
  createMany?: Prisma.MissionCreateManyAgentInputEnvelope
  set?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  disconnect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  delete?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  update?: Prisma.MissionUpdateWithWhereUniqueWithoutAgentInput | Prisma.MissionUpdateWithWhereUniqueWithoutAgentInput[]
  updateMany?: Prisma.MissionUpdateManyWithWhereWithoutAgentInput | Prisma.MissionUpdateManyWithWhereWithoutAgentInput[]
  deleteMany?: Prisma.MissionScalarWhereInput | Prisma.MissionScalarWhereInput[]
}

export type MissionUncheckedUpdateManyWithoutAgentNestedInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutAgentInput, Prisma.MissionUncheckedCreateWithoutAgentInput> | Prisma.MissionCreateWithoutAgentInput[] | Prisma.MissionUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutAgentInput | Prisma.MissionCreateOrConnectWithoutAgentInput[]
  upsert?: Prisma.MissionUpsertWithWhereUniqueWithoutAgentInput | Prisma.MissionUpsertWithWhereUniqueWithoutAgentInput[]
  createMany?: Prisma.MissionCreateManyAgentInputEnvelope
  set?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  disconnect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  delete?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  update?: Prisma.MissionUpdateWithWhereUniqueWithoutAgentInput | Prisma.MissionUpdateWithWhereUniqueWithoutAgentInput[]
  updateMany?: Prisma.MissionUpdateManyWithWhereWithoutAgentInput | Prisma.MissionUpdateManyWithWhereWithoutAgentInput[]
  deleteMany?: Prisma.MissionScalarWhereInput | Prisma.MissionScalarWhereInput[]
}

export type MissionCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutPropertyInput, Prisma.MissionUncheckedCreateWithoutPropertyInput> | Prisma.MissionCreateWithoutPropertyInput[] | Prisma.MissionUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutPropertyInput | Prisma.MissionCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.MissionCreateManyPropertyInputEnvelope
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
}

export type MissionUncheckedCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutPropertyInput, Prisma.MissionUncheckedCreateWithoutPropertyInput> | Prisma.MissionCreateWithoutPropertyInput[] | Prisma.MissionUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutPropertyInput | Prisma.MissionCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.MissionCreateManyPropertyInputEnvelope
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
}

export type MissionUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutPropertyInput, Prisma.MissionUncheckedCreateWithoutPropertyInput> | Prisma.MissionCreateWithoutPropertyInput[] | Prisma.MissionUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutPropertyInput | Prisma.MissionCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.MissionUpsertWithWhereUniqueWithoutPropertyInput | Prisma.MissionUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.MissionCreateManyPropertyInputEnvelope
  set?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  disconnect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  delete?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  update?: Prisma.MissionUpdateWithWhereUniqueWithoutPropertyInput | Prisma.MissionUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.MissionUpdateManyWithWhereWithoutPropertyInput | Prisma.MissionUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.MissionScalarWhereInput | Prisma.MissionScalarWhereInput[]
}

export type MissionUncheckedUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.MissionCreateWithoutPropertyInput, Prisma.MissionUncheckedCreateWithoutPropertyInput> | Prisma.MissionCreateWithoutPropertyInput[] | Prisma.MissionUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MissionCreateOrConnectWithoutPropertyInput | Prisma.MissionCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.MissionUpsertWithWhereUniqueWithoutPropertyInput | Prisma.MissionUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.MissionCreateManyPropertyInputEnvelope
  set?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  disconnect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  delete?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  connect?: Prisma.MissionWhereUniqueInput | Prisma.MissionWhereUniqueInput[]
  update?: Prisma.MissionUpdateWithWhereUniqueWithoutPropertyInput | Prisma.MissionUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.MissionUpdateManyWithWhereWithoutPropertyInput | Prisma.MissionUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.MissionScalarWhereInput | Prisma.MissionScalarWhereInput[]
}

export type EnumMissionStatusFieldUpdateOperationsInput = {
  set?: $Enums.MissionStatus
}

export type MissionCreateWithoutAgentInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutMissionsInput
}

export type MissionUncheckedCreateWithoutAgentInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  propertyId: string
}

export type MissionCreateOrConnectWithoutAgentInput = {
  where: Prisma.MissionWhereUniqueInput
  create: Prisma.XOR<Prisma.MissionCreateWithoutAgentInput, Prisma.MissionUncheckedCreateWithoutAgentInput>
}

export type MissionCreateManyAgentInputEnvelope = {
  data: Prisma.MissionCreateManyAgentInput | Prisma.MissionCreateManyAgentInput[]
  skipDuplicates?: boolean
}

export type MissionUpsertWithWhereUniqueWithoutAgentInput = {
  where: Prisma.MissionWhereUniqueInput
  update: Prisma.XOR<Prisma.MissionUpdateWithoutAgentInput, Prisma.MissionUncheckedUpdateWithoutAgentInput>
  create: Prisma.XOR<Prisma.MissionCreateWithoutAgentInput, Prisma.MissionUncheckedCreateWithoutAgentInput>
}

export type MissionUpdateWithWhereUniqueWithoutAgentInput = {
  where: Prisma.MissionWhereUniqueInput
  data: Prisma.XOR<Prisma.MissionUpdateWithoutAgentInput, Prisma.MissionUncheckedUpdateWithoutAgentInput>
}

export type MissionUpdateManyWithWhereWithoutAgentInput = {
  where: Prisma.MissionScalarWhereInput
  data: Prisma.XOR<Prisma.MissionUpdateManyMutationInput, Prisma.MissionUncheckedUpdateManyWithoutAgentInput>
}

export type MissionScalarWhereInput = {
  AND?: Prisma.MissionScalarWhereInput | Prisma.MissionScalarWhereInput[]
  OR?: Prisma.MissionScalarWhereInput[]
  NOT?: Prisma.MissionScalarWhereInput | Prisma.MissionScalarWhereInput[]
  id?: Prisma.StringFilter<"Mission"> | string
  type?: Prisma.EnumMissionTypeFilter<"Mission"> | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFilter<"Mission"> | $Enums.MissionStatus
  fee?: Prisma.IntFilter<"Mission"> | number
  dateScheduled?: Prisma.DateTimeNullableFilter<"Mission"> | Date | string | null
  reportData?: Prisma.StringNullableFilter<"Mission"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Mission"> | Date | string
  propertyId?: Prisma.StringFilter<"Mission"> | string
  agentId?: Prisma.StringNullableFilter<"Mission"> | string | null
}

export type MissionCreateWithoutPropertyInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  agent?: Prisma.UserCreateNestedOneWithoutMissionsAcceptedInput
}

export type MissionUncheckedCreateWithoutPropertyInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  agentId?: string | null
}

export type MissionCreateOrConnectWithoutPropertyInput = {
  where: Prisma.MissionWhereUniqueInput
  create: Prisma.XOR<Prisma.MissionCreateWithoutPropertyInput, Prisma.MissionUncheckedCreateWithoutPropertyInput>
}

export type MissionCreateManyPropertyInputEnvelope = {
  data: Prisma.MissionCreateManyPropertyInput | Prisma.MissionCreateManyPropertyInput[]
  skipDuplicates?: boolean
}

export type MissionUpsertWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.MissionWhereUniqueInput
  update: Prisma.XOR<Prisma.MissionUpdateWithoutPropertyInput, Prisma.MissionUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.MissionCreateWithoutPropertyInput, Prisma.MissionUncheckedCreateWithoutPropertyInput>
}

export type MissionUpdateWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.MissionWhereUniqueInput
  data: Prisma.XOR<Prisma.MissionUpdateWithoutPropertyInput, Prisma.MissionUncheckedUpdateWithoutPropertyInput>
}

export type MissionUpdateManyWithWhereWithoutPropertyInput = {
  where: Prisma.MissionScalarWhereInput
  data: Prisma.XOR<Prisma.MissionUpdateManyMutationInput, Prisma.MissionUncheckedUpdateManyWithoutPropertyInput>
}

export type MissionCreateManyAgentInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  propertyId: string
}

export type MissionUpdateWithoutAgentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutMissionsNestedInput
}

export type MissionUncheckedUpdateWithoutAgentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MissionUncheckedUpdateManyWithoutAgentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MissionCreateManyPropertyInput = {
  id?: string
  type: $Enums.MissionType
  status?: $Enums.MissionStatus
  fee: number
  dateScheduled?: Date | string | null
  reportData?: string | null
  createdAt?: Date | string
  agentId?: string | null
}

export type MissionUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent?: Prisma.UserUpdateOneWithoutMissionsAcceptedNestedInput
}

export type MissionUncheckedUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MissionUncheckedUpdateManyWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumMissionTypeFieldUpdateOperationsInput | $Enums.MissionType
  status?: Prisma.EnumMissionStatusFieldUpdateOperationsInput | $Enums.MissionStatus
  fee?: Prisma.IntFieldUpdateOperationsInput | number
  dateScheduled?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reportData?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type MissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  status?: boolean
  fee?: boolean
  dateScheduled?: boolean
  reportData?: boolean
  createdAt?: boolean
  propertyId?: boolean
  agentId?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  agent?: boolean | Prisma.Mission$agentArgs<ExtArgs>
}, ExtArgs["result"]["mission"]>

export type MissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  status?: boolean
  fee?: boolean
  dateScheduled?: boolean
  reportData?: boolean
  createdAt?: boolean
  propertyId?: boolean
  agentId?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  agent?: boolean | Prisma.Mission$agentArgs<ExtArgs>
}, ExtArgs["result"]["mission"]>

export type MissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  status?: boolean
  fee?: boolean
  dateScheduled?: boolean
  reportData?: boolean
  createdAt?: boolean
  propertyId?: boolean
  agentId?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  agent?: boolean | Prisma.Mission$agentArgs<ExtArgs>
}, ExtArgs["result"]["mission"]>

export type MissionSelectScalar = {
  id?: boolean
  type?: boolean
  status?: boolean
  fee?: boolean
  dateScheduled?: boolean
  reportData?: boolean
  createdAt?: boolean
  propertyId?: boolean
  agentId?: boolean
}

export type MissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "status" | "fee" | "dateScheduled" | "reportData" | "createdAt" | "propertyId" | "agentId", ExtArgs["result"]["mission"]>
export type MissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  agent?: boolean | Prisma.Mission$agentArgs<ExtArgs>
}
export type MissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  agent?: boolean | Prisma.Mission$agentArgs<ExtArgs>
}
export type MissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  agent?: boolean | Prisma.Mission$agentArgs<ExtArgs>
}

export type $MissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Mission"
  objects: {
    property: Prisma.$PropertyPayload<ExtArgs>
    agent: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.MissionType
    status: $Enums.MissionStatus
    fee: number
    dateScheduled: Date | null
    reportData: string | null
    createdAt: Date
    propertyId: string
    agentId: string | null
  }, ExtArgs["result"]["mission"]>
  composites: {}
}

export type MissionGetPayload<S extends boolean | null | undefined | MissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MissionPayload, S>

export type MissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MissionCountAggregateInputType | true
  }

export interface MissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Mission'], meta: { name: 'Mission' } }
  /**
   * Find zero or one Mission that matches the filter.
   * @param {MissionFindUniqueArgs} args - Arguments to find a Mission
   * @example
   * // Get one Mission
   * const mission = await prisma.mission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MissionFindUniqueArgs>(args: Prisma.SelectSubset<T, MissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MissionFindUniqueOrThrowArgs} args - Arguments to find a Mission
   * @example
   * // Get one Mission
   * const mission = await prisma.mission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionFindFirstArgs} args - Arguments to find a Mission
   * @example
   * // Get one Mission
   * const mission = await prisma.mission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MissionFindFirstArgs>(args?: Prisma.SelectSubset<T, MissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionFindFirstOrThrowArgs} args - Arguments to find a Mission
   * @example
   * // Get one Mission
   * const mission = await prisma.mission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Missions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Missions
   * const missions = await prisma.mission.findMany()
   * 
   * // Get first 10 Missions
   * const missions = await prisma.mission.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const missionWithIdOnly = await prisma.mission.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MissionFindManyArgs>(args?: Prisma.SelectSubset<T, MissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mission.
   * @param {MissionCreateArgs} args - Arguments to create a Mission.
   * @example
   * // Create one Mission
   * const Mission = await prisma.mission.create({
   *   data: {
   *     // ... data to create a Mission
   *   }
   * })
   * 
   */
  create<T extends MissionCreateArgs>(args: Prisma.SelectSubset<T, MissionCreateArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Missions.
   * @param {MissionCreateManyArgs} args - Arguments to create many Missions.
   * @example
   * // Create many Missions
   * const mission = await prisma.mission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MissionCreateManyArgs>(args?: Prisma.SelectSubset<T, MissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Missions and returns the data saved in the database.
   * @param {MissionCreateManyAndReturnArgs} args - Arguments to create many Missions.
   * @example
   * // Create many Missions
   * const mission = await prisma.mission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Missions and only return the `id`
   * const missionWithIdOnly = await prisma.mission.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mission.
   * @param {MissionDeleteArgs} args - Arguments to delete one Mission.
   * @example
   * // Delete one Mission
   * const Mission = await prisma.mission.delete({
   *   where: {
   *     // ... filter to delete one Mission
   *   }
   * })
   * 
   */
  delete<T extends MissionDeleteArgs>(args: Prisma.SelectSubset<T, MissionDeleteArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mission.
   * @param {MissionUpdateArgs} args - Arguments to update one Mission.
   * @example
   * // Update one Mission
   * const mission = await prisma.mission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MissionUpdateArgs>(args: Prisma.SelectSubset<T, MissionUpdateArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Missions.
   * @param {MissionDeleteManyArgs} args - Arguments to filter Missions to delete.
   * @example
   * // Delete a few Missions
   * const { count } = await prisma.mission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, MissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Missions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Missions
   * const mission = await prisma.mission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MissionUpdateManyArgs>(args: Prisma.SelectSubset<T, MissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Missions and returns the data updated in the database.
   * @param {MissionUpdateManyAndReturnArgs} args - Arguments to update many Missions.
   * @example
   * // Update many Missions
   * const mission = await prisma.mission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Missions and only return the `id`
   * const missionWithIdOnly = await prisma.mission.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mission.
   * @param {MissionUpsertArgs} args - Arguments to update or create a Mission.
   * @example
   * // Update or create a Mission
   * const mission = await prisma.mission.upsert({
   *   create: {
   *     // ... data to create a Mission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mission we want to update
   *   }
   * })
   */
  upsert<T extends MissionUpsertArgs>(args: Prisma.SelectSubset<T, MissionUpsertArgs<ExtArgs>>): Prisma.Prisma__MissionClient<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Missions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionCountArgs} args - Arguments to filter Missions to count.
   * @example
   * // Count the number of Missions
   * const count = await prisma.mission.count({
   *   where: {
   *     // ... the filter for the Missions we want to count
   *   }
   * })
  **/
  count<T extends MissionCountArgs>(
    args?: Prisma.Subset<T, MissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MissionAggregateArgs>(args: Prisma.Subset<T, MissionAggregateArgs>): Prisma.PrismaPromise<GetMissionAggregateType<T>>

  /**
   * Group by Mission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MissionGroupByArgs['orderBy'] }
      : { orderBy?: MissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Mission model
 */
readonly fields: MissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Mission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  property<T extends Prisma.PropertyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PropertyDefaultArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  agent<T extends Prisma.Mission$agentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Mission$agentArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Mission model
 */
export interface MissionFieldRefs {
  readonly id: Prisma.FieldRef<"Mission", 'String'>
  readonly type: Prisma.FieldRef<"Mission", 'MissionType'>
  readonly status: Prisma.FieldRef<"Mission", 'MissionStatus'>
  readonly fee: Prisma.FieldRef<"Mission", 'Int'>
  readonly dateScheduled: Prisma.FieldRef<"Mission", 'DateTime'>
  readonly reportData: Prisma.FieldRef<"Mission", 'String'>
  readonly createdAt: Prisma.FieldRef<"Mission", 'DateTime'>
  readonly propertyId: Prisma.FieldRef<"Mission", 'String'>
  readonly agentId: Prisma.FieldRef<"Mission", 'String'>
}
    

// Custom InputTypes
/**
 * Mission findUnique
 */
export type MissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * Filter, which Mission to fetch.
   */
  where: Prisma.MissionWhereUniqueInput
}

/**
 * Mission findUniqueOrThrow
 */
export type MissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * Filter, which Mission to fetch.
   */
  where: Prisma.MissionWhereUniqueInput
}

/**
 * Mission findFirst
 */
export type MissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * Filter, which Mission to fetch.
   */
  where?: Prisma.MissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Missions to fetch.
   */
  orderBy?: Prisma.MissionOrderByWithRelationInput | Prisma.MissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Missions.
   */
  cursor?: Prisma.MissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Missions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Missions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Missions.
   */
  distinct?: Prisma.MissionScalarFieldEnum | Prisma.MissionScalarFieldEnum[]
}

/**
 * Mission findFirstOrThrow
 */
export type MissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * Filter, which Mission to fetch.
   */
  where?: Prisma.MissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Missions to fetch.
   */
  orderBy?: Prisma.MissionOrderByWithRelationInput | Prisma.MissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Missions.
   */
  cursor?: Prisma.MissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Missions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Missions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Missions.
   */
  distinct?: Prisma.MissionScalarFieldEnum | Prisma.MissionScalarFieldEnum[]
}

/**
 * Mission findMany
 */
export type MissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * Filter, which Missions to fetch.
   */
  where?: Prisma.MissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Missions to fetch.
   */
  orderBy?: Prisma.MissionOrderByWithRelationInput | Prisma.MissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Missions.
   */
  cursor?: Prisma.MissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Missions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Missions.
   */
  skip?: number
  distinct?: Prisma.MissionScalarFieldEnum | Prisma.MissionScalarFieldEnum[]
}

/**
 * Mission create
 */
export type MissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * The data needed to create a Mission.
   */
  data: Prisma.XOR<Prisma.MissionCreateInput, Prisma.MissionUncheckedCreateInput>
}

/**
 * Mission createMany
 */
export type MissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Missions.
   */
  data: Prisma.MissionCreateManyInput | Prisma.MissionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Mission createManyAndReturn
 */
export type MissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * The data used to create many Missions.
   */
  data: Prisma.MissionCreateManyInput | Prisma.MissionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Mission update
 */
export type MissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * The data needed to update a Mission.
   */
  data: Prisma.XOR<Prisma.MissionUpdateInput, Prisma.MissionUncheckedUpdateInput>
  /**
   * Choose, which Mission to update.
   */
  where: Prisma.MissionWhereUniqueInput
}

/**
 * Mission updateMany
 */
export type MissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Missions.
   */
  data: Prisma.XOR<Prisma.MissionUpdateManyMutationInput, Prisma.MissionUncheckedUpdateManyInput>
  /**
   * Filter which Missions to update
   */
  where?: Prisma.MissionWhereInput
  /**
   * Limit how many Missions to update.
   */
  limit?: number
}

/**
 * Mission updateManyAndReturn
 */
export type MissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * The data used to update Missions.
   */
  data: Prisma.XOR<Prisma.MissionUpdateManyMutationInput, Prisma.MissionUncheckedUpdateManyInput>
  /**
   * Filter which Missions to update
   */
  where?: Prisma.MissionWhereInput
  /**
   * Limit how many Missions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Mission upsert
 */
export type MissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * The filter to search for the Mission to update in case it exists.
   */
  where: Prisma.MissionWhereUniqueInput
  /**
   * In case the Mission found by the `where` argument doesn't exist, create a new Mission with this data.
   */
  create: Prisma.XOR<Prisma.MissionCreateInput, Prisma.MissionUncheckedCreateInput>
  /**
   * In case the Mission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MissionUpdateInput, Prisma.MissionUncheckedUpdateInput>
}

/**
 * Mission delete
 */
export type MissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  /**
   * Filter which Mission to delete.
   */
  where: Prisma.MissionWhereUniqueInput
}

/**
 * Mission deleteMany
 */
export type MissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Missions to delete
   */
  where?: Prisma.MissionWhereInput
  /**
   * Limit how many Missions to delete.
   */
  limit?: number
}

/**
 * Mission.agent
 */
export type Mission$agentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Mission without action
 */
export type MissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
}
