
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Property` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Property
 * 
 */
export type PropertyModel = runtime.Types.Result.DefaultSelection<Prisma.$PropertyPayload>

export type AggregateProperty = {
  _count: PropertyCountAggregateOutputType | null
  _avg: PropertyAvgAggregateOutputType | null
  _sum: PropertySumAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

export type PropertyAvgAggregateOutputType = {
  price: number | null
  bedrooms: number | null
  bathrooms: number | null
  surface: number | null
}

export type PropertySumAggregateOutputType = {
  price: number | null
  bedrooms: number | null
  bathrooms: number | null
  surface: number | null
}

export type PropertyMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  address: string | null
  commune: string | null
  price: number | null
  type: $Enums.PropertyType | null
  bedrooms: number | null
  bathrooms: number | null
  surface: number | null
  isPublished: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  ownerId: string | null
}

export type PropertyMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  address: string | null
  commune: string | null
  price: number | null
  type: $Enums.PropertyType | null
  bedrooms: number | null
  bathrooms: number | null
  surface: number | null
  isPublished: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  ownerId: string | null
}

export type PropertyCountAggregateOutputType = {
  id: number
  title: number
  description: number
  address: number
  commune: number
  price: number
  type: number
  bedrooms: number
  bathrooms: number
  surface: number
  images: number
  isPublished: number
  createdAt: number
  updatedAt: number
  ownerId: number
  _all: number
}


export type PropertyAvgAggregateInputType = {
  price?: true
  bedrooms?: true
  bathrooms?: true
  surface?: true
}

export type PropertySumAggregateInputType = {
  price?: true
  bedrooms?: true
  bathrooms?: true
  surface?: true
}

export type PropertyMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  address?: true
  commune?: true
  price?: true
  type?: true
  bedrooms?: true
  bathrooms?: true
  surface?: true
  isPublished?: true
  createdAt?: true
  updatedAt?: true
  ownerId?: true
}

export type PropertyMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  address?: true
  commune?: true
  price?: true
  type?: true
  bedrooms?: true
  bathrooms?: true
  surface?: true
  isPublished?: true
  createdAt?: true
  updatedAt?: true
  ownerId?: true
}

export type PropertyCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  address?: true
  commune?: true
  price?: true
  type?: true
  bedrooms?: true
  bathrooms?: true
  surface?: true
  images?: true
  isPublished?: true
  createdAt?: true
  updatedAt?: true
  ownerId?: true
  _all?: true
}

export type PropertyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Property to aggregate.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Properties
  **/
  _count?: true | PropertyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PropertyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PropertySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PropertyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PropertyMaxAggregateInputType
}

export type GetPropertyAggregateType<T extends PropertyAggregateArgs> = {
      [P in keyof T & keyof AggregateProperty]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProperty[P]>
    : Prisma.GetScalarType<T[P], AggregateProperty[P]>
}




export type PropertyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyWhereInput
  orderBy?: Prisma.PropertyOrderByWithAggregationInput | Prisma.PropertyOrderByWithAggregationInput[]
  by: Prisma.PropertyScalarFieldEnum[] | Prisma.PropertyScalarFieldEnum
  having?: Prisma.PropertyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PropertyCountAggregateInputType | true
  _avg?: PropertyAvgAggregateInputType
  _sum?: PropertySumAggregateInputType
  _min?: PropertyMinAggregateInputType
  _max?: PropertyMaxAggregateInputType
}

export type PropertyGroupByOutputType = {
  id: string
  title: string
  description: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface: number | null
  images: string[]
  isPublished: boolean
  createdAt: Date
  updatedAt: Date
  ownerId: string
  _count: PropertyCountAggregateOutputType | null
  _avg: PropertyAvgAggregateOutputType | null
  _sum: PropertySumAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

type GetPropertyGroupByPayload<T extends PropertyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PropertyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PropertyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
      }
    >
  >



export type PropertyWhereInput = {
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  id?: Prisma.StringFilter<"Property"> | string
  title?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringNullableFilter<"Property"> | string | null
  address?: Prisma.StringFilter<"Property"> | string
  commune?: Prisma.StringFilter<"Property"> | string
  price?: Prisma.IntFilter<"Property"> | number
  type?: Prisma.EnumPropertyTypeFilter<"Property"> | $Enums.PropertyType
  bedrooms?: Prisma.IntFilter<"Property"> | number
  bathrooms?: Prisma.IntFilter<"Property"> | number
  surface?: Prisma.FloatNullableFilter<"Property"> | number | null
  images?: Prisma.StringNullableListFilter<"Property">
  isPublished?: Prisma.BoolFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  ownerId?: Prisma.StringFilter<"Property"> | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  leases?: Prisma.LeaseListRelationFilter
  incidents?: Prisma.IncidentListRelationFilter
  missions?: Prisma.MissionListRelationFilter
  inventories?: Prisma.InventoryListRelationFilter
}

export type PropertyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrder
  commune?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  owner?: Prisma.UserOrderByWithRelationInput
  leases?: Prisma.LeaseOrderByRelationAggregateInput
  incidents?: Prisma.IncidentOrderByRelationAggregateInput
  missions?: Prisma.MissionOrderByRelationAggregateInput
  inventories?: Prisma.InventoryOrderByRelationAggregateInput
}

export type PropertyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  title?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringNullableFilter<"Property"> | string | null
  address?: Prisma.StringFilter<"Property"> | string
  commune?: Prisma.StringFilter<"Property"> | string
  price?: Prisma.IntFilter<"Property"> | number
  type?: Prisma.EnumPropertyTypeFilter<"Property"> | $Enums.PropertyType
  bedrooms?: Prisma.IntFilter<"Property"> | number
  bathrooms?: Prisma.IntFilter<"Property"> | number
  surface?: Prisma.FloatNullableFilter<"Property"> | number | null
  images?: Prisma.StringNullableListFilter<"Property">
  isPublished?: Prisma.BoolFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  ownerId?: Prisma.StringFilter<"Property"> | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  leases?: Prisma.LeaseListRelationFilter
  incidents?: Prisma.IncidentListRelationFilter
  missions?: Prisma.MissionListRelationFilter
  inventories?: Prisma.InventoryListRelationFilter
}, "id">

export type PropertyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrder
  commune?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  _count?: Prisma.PropertyCountOrderByAggregateInput
  _avg?: Prisma.PropertyAvgOrderByAggregateInput
  _max?: Prisma.PropertyMaxOrderByAggregateInput
  _min?: Prisma.PropertyMinOrderByAggregateInput
  _sum?: Prisma.PropertySumOrderByAggregateInput
}

export type PropertyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PropertyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Property"> | string
  title?: Prisma.StringWithAggregatesFilter<"Property"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Property"> | string | null
  address?: Prisma.StringWithAggregatesFilter<"Property"> | string
  commune?: Prisma.StringWithAggregatesFilter<"Property"> | string
  price?: Prisma.IntWithAggregatesFilter<"Property"> | number
  type?: Prisma.EnumPropertyTypeWithAggregatesFilter<"Property"> | $Enums.PropertyType
  bedrooms?: Prisma.IntWithAggregatesFilter<"Property"> | number
  bathrooms?: Prisma.IntWithAggregatesFilter<"Property"> | number
  surface?: Prisma.FloatNullableWithAggregatesFilter<"Property"> | number | null
  images?: Prisma.StringNullableListFilter<"Property">
  isPublished?: Prisma.BoolWithAggregatesFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
  ownerId?: Prisma.StringWithAggregatesFilter<"Property"> | string
}

export type PropertyCreateInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutPropertiesOwnedInput
  leases?: Prisma.LeaseCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerId: string
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionUncheckedCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutPropertiesOwnedNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUncheckedUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerId: string
}

export type PropertyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PropertyListRelationFilter = {
  every?: Prisma.PropertyWhereInput
  some?: Prisma.PropertyWhereInput
  none?: Prisma.PropertyWhereInput
}

export type PropertyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PropertyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  commune?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrder
  images?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type PropertyAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrder
}

export type PropertyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  commune?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type PropertyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  address?: Prisma.SortOrder
  commune?: Prisma.SortOrder
  price?: Prisma.SortOrder
  type?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type PropertySumOrderByAggregateInput = {
  price?: Prisma.SortOrder
  bedrooms?: Prisma.SortOrder
  bathrooms?: Prisma.SortOrder
  surface?: Prisma.SortOrder
}

export type PropertyScalarRelationFilter = {
  is?: Prisma.PropertyWhereInput
  isNot?: Prisma.PropertyWhereInput
}

export type PropertyCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOwnerInput, Prisma.PropertyUncheckedCreateWithoutOwnerInput> | Prisma.PropertyCreateWithoutOwnerInput[] | Prisma.PropertyUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOwnerInput | Prisma.PropertyCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.PropertyCreateManyOwnerInputEnvelope
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
}

export type PropertyUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOwnerInput, Prisma.PropertyUncheckedCreateWithoutOwnerInput> | Prisma.PropertyCreateWithoutOwnerInput[] | Prisma.PropertyUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOwnerInput | Prisma.PropertyCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.PropertyCreateManyOwnerInputEnvelope
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
}

export type PropertyUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOwnerInput, Prisma.PropertyUncheckedCreateWithoutOwnerInput> | Prisma.PropertyCreateWithoutOwnerInput[] | Prisma.PropertyUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOwnerInput | Prisma.PropertyCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.PropertyUpsertWithWhereUniqueWithoutOwnerInput | Prisma.PropertyUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.PropertyCreateManyOwnerInputEnvelope
  set?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  disconnect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  delete?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  update?: Prisma.PropertyUpdateWithWhereUniqueWithoutOwnerInput | Prisma.PropertyUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.PropertyUpdateManyWithWhereWithoutOwnerInput | Prisma.PropertyUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
}

export type PropertyUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutOwnerInput, Prisma.PropertyUncheckedCreateWithoutOwnerInput> | Prisma.PropertyCreateWithoutOwnerInput[] | Prisma.PropertyUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutOwnerInput | Prisma.PropertyCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.PropertyUpsertWithWhereUniqueWithoutOwnerInput | Prisma.PropertyUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.PropertyCreateManyOwnerInputEnvelope
  set?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  disconnect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  delete?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  connect?: Prisma.PropertyWhereUniqueInput | Prisma.PropertyWhereUniqueInput[]
  update?: Prisma.PropertyUpdateWithWhereUniqueWithoutOwnerInput | Prisma.PropertyUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.PropertyUpdateManyWithWhereWithoutOwnerInput | Prisma.PropertyUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
}

export type PropertyCreateimagesInput = {
  set: string[]
}

export type EnumPropertyTypeFieldUpdateOperationsInput = {
  set?: $Enums.PropertyType
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PropertyUpdateimagesInput = {
  set?: string[]
  push?: string | string[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type PropertyCreateNestedOneWithoutLeasesInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutLeasesInput, Prisma.PropertyUncheckedCreateWithoutLeasesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutLeasesInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutLeasesNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutLeasesInput, Prisma.PropertyUncheckedCreateWithoutLeasesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutLeasesInput
  upsert?: Prisma.PropertyUpsertWithoutLeasesInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutLeasesInput, Prisma.PropertyUpdateWithoutLeasesInput>, Prisma.PropertyUncheckedUpdateWithoutLeasesInput>
}

export type PropertyCreateNestedOneWithoutInventoriesInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutInventoriesInput, Prisma.PropertyUncheckedCreateWithoutInventoriesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutInventoriesInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutInventoriesNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutInventoriesInput, Prisma.PropertyUncheckedCreateWithoutInventoriesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutInventoriesInput
  upsert?: Prisma.PropertyUpsertWithoutInventoriesInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutInventoriesInput, Prisma.PropertyUpdateWithoutInventoriesInput>, Prisma.PropertyUncheckedUpdateWithoutInventoriesInput>
}

export type PropertyCreateNestedOneWithoutMissionsInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutMissionsInput, Prisma.PropertyUncheckedCreateWithoutMissionsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutMissionsInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutMissionsNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutMissionsInput, Prisma.PropertyUncheckedCreateWithoutMissionsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutMissionsInput
  upsert?: Prisma.PropertyUpsertWithoutMissionsInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutMissionsInput, Prisma.PropertyUpdateWithoutMissionsInput>, Prisma.PropertyUncheckedUpdateWithoutMissionsInput>
}

export type PropertyCreateNestedOneWithoutIncidentsInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutIncidentsInput, Prisma.PropertyUncheckedCreateWithoutIncidentsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutIncidentsInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutIncidentsNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutIncidentsInput, Prisma.PropertyUncheckedCreateWithoutIncidentsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutIncidentsInput
  upsert?: Prisma.PropertyUpsertWithoutIncidentsInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutIncidentsInput, Prisma.PropertyUpdateWithoutIncidentsInput>, Prisma.PropertyUncheckedUpdateWithoutIncidentsInput>
}

export type PropertyCreateWithoutOwnerInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  leases?: Prisma.LeaseCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutOwnerInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionUncheckedCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutOwnerInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutOwnerInput, Prisma.PropertyUncheckedCreateWithoutOwnerInput>
}

export type PropertyCreateManyOwnerInputEnvelope = {
  data: Prisma.PropertyCreateManyOwnerInput | Prisma.PropertyCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type PropertyUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.PropertyWhereUniqueInput
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutOwnerInput, Prisma.PropertyUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutOwnerInput, Prisma.PropertyUncheckedCreateWithoutOwnerInput>
}

export type PropertyUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.PropertyWhereUniqueInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutOwnerInput, Prisma.PropertyUncheckedUpdateWithoutOwnerInput>
}

export type PropertyUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.PropertyScalarWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyWithoutOwnerInput>
}

export type PropertyScalarWhereInput = {
  AND?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
  OR?: Prisma.PropertyScalarWhereInput[]
  NOT?: Prisma.PropertyScalarWhereInput | Prisma.PropertyScalarWhereInput[]
  id?: Prisma.StringFilter<"Property"> | string
  title?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringNullableFilter<"Property"> | string | null
  address?: Prisma.StringFilter<"Property"> | string
  commune?: Prisma.StringFilter<"Property"> | string
  price?: Prisma.IntFilter<"Property"> | number
  type?: Prisma.EnumPropertyTypeFilter<"Property"> | $Enums.PropertyType
  bedrooms?: Prisma.IntFilter<"Property"> | number
  bathrooms?: Prisma.IntFilter<"Property"> | number
  surface?: Prisma.FloatNullableFilter<"Property"> | number | null
  images?: Prisma.StringNullableListFilter<"Property">
  isPublished?: Prisma.BoolFilter<"Property"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  ownerId?: Prisma.StringFilter<"Property"> | string
}

export type PropertyCreateWithoutLeasesInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutPropertiesOwnedInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutLeasesInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerId: string
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionUncheckedCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutLeasesInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutLeasesInput, Prisma.PropertyUncheckedCreateWithoutLeasesInput>
}

export type PropertyUpsertWithoutLeasesInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutLeasesInput, Prisma.PropertyUncheckedUpdateWithoutLeasesInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutLeasesInput, Prisma.PropertyUncheckedCreateWithoutLeasesInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutLeasesInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutLeasesInput, Prisma.PropertyUncheckedUpdateWithoutLeasesInput>
}

export type PropertyUpdateWithoutLeasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutPropertiesOwnedNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutLeasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUncheckedUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutInventoriesInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutPropertiesOwnedInput
  leases?: Prisma.LeaseCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutInventoriesInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerId: string
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutInventoriesInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutInventoriesInput, Prisma.PropertyUncheckedCreateWithoutInventoriesInput>
}

export type PropertyUpsertWithoutInventoriesInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutInventoriesInput, Prisma.PropertyUncheckedUpdateWithoutInventoriesInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutInventoriesInput, Prisma.PropertyUncheckedCreateWithoutInventoriesInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutInventoriesInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutInventoriesInput, Prisma.PropertyUncheckedUpdateWithoutInventoriesInput>
}

export type PropertyUpdateWithoutInventoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutPropertiesOwnedNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutInventoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutMissionsInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutPropertiesOwnedInput
  leases?: Prisma.LeaseCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutMissionsInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerId: string
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutPropertyInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutMissionsInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutMissionsInput, Prisma.PropertyUncheckedCreateWithoutMissionsInput>
}

export type PropertyUpsertWithoutMissionsInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutMissionsInput, Prisma.PropertyUncheckedUpdateWithoutMissionsInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutMissionsInput, Prisma.PropertyUncheckedCreateWithoutMissionsInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutMissionsInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutMissionsInput, Prisma.PropertyUncheckedUpdateWithoutMissionsInput>
}

export type PropertyUpdateWithoutMissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutPropertiesOwnedNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutMissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutIncidentsInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutPropertiesOwnedInput
  leases?: Prisma.LeaseCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutIncidentsInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerId: string
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutPropertyInput
  missions?: Prisma.MissionUncheckedCreateNestedManyWithoutPropertyInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutIncidentsInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutIncidentsInput, Prisma.PropertyUncheckedCreateWithoutIncidentsInput>
}

export type PropertyUpsertWithoutIncidentsInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutIncidentsInput, Prisma.PropertyUncheckedUpdateWithoutIncidentsInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutIncidentsInput, Prisma.PropertyUncheckedCreateWithoutIncidentsInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutIncidentsInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutIncidentsInput, Prisma.PropertyUncheckedUpdateWithoutIncidentsInput>
}

export type PropertyUpdateWithoutIncidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutPropertiesOwnedNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutIncidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUncheckedUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateManyOwnerInput = {
  id?: string
  title: string
  description?: string | null
  address: string
  commune: string
  price: number
  type: $Enums.PropertyType
  bedrooms: number
  bathrooms: number
  surface?: number | null
  images?: Prisma.PropertyCreateimagesInput | string[]
  isPublished?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PropertyUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  leases?: Prisma.LeaseUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutPropertyNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutPropertyNestedInput
  missions?: Prisma.MissionUncheckedUpdateManyWithoutPropertyNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.StringFieldUpdateOperationsInput | string
  commune?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumPropertyTypeFieldUpdateOperationsInput | $Enums.PropertyType
  bedrooms?: Prisma.IntFieldUpdateOperationsInput | number
  bathrooms?: Prisma.IntFieldUpdateOperationsInput | number
  surface?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  images?: Prisma.PropertyUpdateimagesInput | string[]
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PropertyCountOutputType
 */

export type PropertyCountOutputType = {
  leases: number
  incidents: number
  missions: number
  inventories: number
}

export type PropertyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  leases?: boolean | PropertyCountOutputTypeCountLeasesArgs
  incidents?: boolean | PropertyCountOutputTypeCountIncidentsArgs
  missions?: boolean | PropertyCountOutputTypeCountMissionsArgs
  inventories?: boolean | PropertyCountOutputTypeCountInventoriesArgs
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PropertyCountOutputType
   */
  select?: Prisma.PropertyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountLeasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeaseWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountIncidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncidentWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountMissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MissionWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountInventoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InventoryWhereInput
}


export type PropertySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  address?: boolean
  commune?: boolean
  price?: boolean
  type?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  surface?: boolean
  images?: boolean
  isPublished?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerId?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  leases?: boolean | Prisma.Property$leasesArgs<ExtArgs>
  incidents?: boolean | Prisma.Property$incidentsArgs<ExtArgs>
  missions?: boolean | Prisma.Property$missionsArgs<ExtArgs>
  inventories?: boolean | Prisma.Property$inventoriesArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  address?: boolean
  commune?: boolean
  price?: boolean
  type?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  surface?: boolean
  images?: boolean
  isPublished?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerId?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  address?: boolean
  commune?: boolean
  price?: boolean
  type?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  surface?: boolean
  images?: boolean
  isPublished?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerId?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property"]>

export type PropertySelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  address?: boolean
  commune?: boolean
  price?: boolean
  type?: boolean
  bedrooms?: boolean
  bathrooms?: boolean
  surface?: boolean
  images?: boolean
  isPublished?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerId?: boolean
}

export type PropertyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "address" | "commune" | "price" | "type" | "bedrooms" | "bathrooms" | "surface" | "images" | "isPublished" | "createdAt" | "updatedAt" | "ownerId", ExtArgs["result"]["property"]>
export type PropertyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  leases?: boolean | Prisma.Property$leasesArgs<ExtArgs>
  incidents?: boolean | Prisma.Property$incidentsArgs<ExtArgs>
  missions?: boolean | Prisma.Property$missionsArgs<ExtArgs>
  inventories?: boolean | Prisma.Property$inventoriesArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}
export type PropertyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PropertyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PropertyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Property"
  objects: {
    owner: Prisma.$UserPayload<ExtArgs>
    leases: Prisma.$LeasePayload<ExtArgs>[]
    incidents: Prisma.$IncidentPayload<ExtArgs>[]
    missions: Prisma.$MissionPayload<ExtArgs>[]
    inventories: Prisma.$InventoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    address: string
    commune: string
    price: number
    type: $Enums.PropertyType
    bedrooms: number
    bathrooms: number
    surface: number | null
    images: string[]
    isPublished: boolean
    createdAt: Date
    updatedAt: Date
    ownerId: string
  }, ExtArgs["result"]["property"]>
  composites: {}
}

export type PropertyGetPayload<S extends boolean | null | undefined | PropertyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PropertyPayload, S>

export type PropertyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PropertyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PropertyCountAggregateInputType | true
  }

export interface PropertyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Property'], meta: { name: 'Property' } }
  /**
   * Find zero or one Property that matches the filter.
   * @param {PropertyFindUniqueArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PropertyFindUniqueArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Property that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PropertyFindUniqueOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PropertyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PropertyFindFirstArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PropertyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Properties that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Properties
   * const properties = await prisma.property.findMany()
   * 
   * // Get first 10 Properties
   * const properties = await prisma.property.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const propertyWithIdOnly = await prisma.property.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PropertyFindManyArgs>(args?: Prisma.SelectSubset<T, PropertyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Property.
   * @param {PropertyCreateArgs} args - Arguments to create a Property.
   * @example
   * // Create one Property
   * const Property = await prisma.property.create({
   *   data: {
   *     // ... data to create a Property
   *   }
   * })
   * 
   */
  create<T extends PropertyCreateArgs>(args: Prisma.SelectSubset<T, PropertyCreateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Properties.
   * @param {PropertyCreateManyArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PropertyCreateManyArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Properties and returns the data saved in the database.
   * @param {PropertyCreateManyAndReturnArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Properties and only return the `id`
   * const propertyWithIdOnly = await prisma.property.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PropertyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Property.
   * @param {PropertyDeleteArgs} args - Arguments to delete one Property.
   * @example
   * // Delete one Property
   * const Property = await prisma.property.delete({
   *   where: {
   *     // ... filter to delete one Property
   *   }
   * })
   * 
   */
  delete<T extends PropertyDeleteArgs>(args: Prisma.SelectSubset<T, PropertyDeleteArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Property.
   * @param {PropertyUpdateArgs} args - Arguments to update one Property.
   * @example
   * // Update one Property
   * const property = await prisma.property.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PropertyUpdateArgs>(args: Prisma.SelectSubset<T, PropertyUpdateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Properties.
   * @param {PropertyDeleteManyArgs} args - Arguments to filter Properties to delete.
   * @example
   * // Delete a few Properties
   * const { count } = await prisma.property.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PropertyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PropertyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PropertyUpdateManyArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties and returns the data updated in the database.
   * @param {PropertyUpdateManyAndReturnArgs} args - Arguments to update many Properties.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Properties and only return the `id`
   * const propertyWithIdOnly = await prisma.property.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PropertyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Property.
   * @param {PropertyUpsertArgs} args - Arguments to update or create a Property.
   * @example
   * // Update or create a Property
   * const property = await prisma.property.upsert({
   *   create: {
   *     // ... data to create a Property
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Property we want to update
   *   }
   * })
   */
  upsert<T extends PropertyUpsertArgs>(args: Prisma.SelectSubset<T, PropertyUpsertArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyCountArgs} args - Arguments to filter Properties to count.
   * @example
   * // Count the number of Properties
   * const count = await prisma.property.count({
   *   where: {
   *     // ... the filter for the Properties we want to count
   *   }
   * })
  **/
  count<T extends PropertyCountArgs>(
    args?: Prisma.Subset<T, PropertyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PropertyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PropertyAggregateArgs>(args: Prisma.Subset<T, PropertyAggregateArgs>): Prisma.PrismaPromise<GetPropertyAggregateType<T>>

  /**
   * Group by Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PropertyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PropertyGroupByArgs['orderBy'] }
      : { orderBy?: PropertyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PropertyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPropertyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Property model
 */
readonly fields: PropertyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Property.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PropertyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  leases<T extends Prisma.Property$leasesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$leasesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  incidents<T extends Prisma.Property$incidentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$incidentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  missions<T extends Prisma.Property$missionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$missionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  inventories<T extends Prisma.Property$inventoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$inventoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InventoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Property model
 */
export interface PropertyFieldRefs {
  readonly id: Prisma.FieldRef<"Property", 'String'>
  readonly title: Prisma.FieldRef<"Property", 'String'>
  readonly description: Prisma.FieldRef<"Property", 'String'>
  readonly address: Prisma.FieldRef<"Property", 'String'>
  readonly commune: Prisma.FieldRef<"Property", 'String'>
  readonly price: Prisma.FieldRef<"Property", 'Int'>
  readonly type: Prisma.FieldRef<"Property", 'PropertyType'>
  readonly bedrooms: Prisma.FieldRef<"Property", 'Int'>
  readonly bathrooms: Prisma.FieldRef<"Property", 'Int'>
  readonly surface: Prisma.FieldRef<"Property", 'Float'>
  readonly images: Prisma.FieldRef<"Property", 'String[]'>
  readonly isPublished: Prisma.FieldRef<"Property", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Property", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Property", 'DateTime'>
  readonly ownerId: Prisma.FieldRef<"Property", 'String'>
}
    

// Custom InputTypes
/**
 * Property findUnique
 */
export type PropertyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findUniqueOrThrow
 */
export type PropertyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findFirst
 */
export type PropertyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findFirstOrThrow
 */
export type PropertyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findMany
 */
export type PropertyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Properties to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property create
 */
export type PropertyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to create a Property.
   */
  data: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
}

/**
 * Property createMany
 */
export type PropertyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Property createManyAndReturn
 */
export type PropertyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Property update
 */
export type PropertyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to update a Property.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
  /**
   * Choose, which Property to update.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property updateMany
 */
export type PropertyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
}

/**
 * Property updateManyAndReturn
 */
export type PropertyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Property upsert
 */
export type PropertyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The filter to search for the Property to update in case it exists.
   */
  where: Prisma.PropertyWhereUniqueInput
  /**
   * In case the Property found by the `where` argument doesn't exist, create a new Property with this data.
   */
  create: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
  /**
   * In case the Property was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
}

/**
 * Property delete
 */
export type PropertyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter which Property to delete.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property deleteMany
 */
export type PropertyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Properties to delete
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to delete.
   */
  limit?: number
}

/**
 * Property.leases
 */
export type Property$leasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  where?: Prisma.LeaseWhereInput
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  cursor?: Prisma.LeaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Property.incidents
 */
export type Property$incidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  where?: Prisma.IncidentWhereInput
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  cursor?: Prisma.IncidentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.IncidentScalarFieldEnum | Prisma.IncidentScalarFieldEnum[]
}

/**
 * Property.missions
 */
export type Property$missionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mission
   */
  select?: Prisma.MissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mission
   */
  omit?: Prisma.MissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MissionInclude<ExtArgs> | null
  where?: Prisma.MissionWhereInput
  orderBy?: Prisma.MissionOrderByWithRelationInput | Prisma.MissionOrderByWithRelationInput[]
  cursor?: Prisma.MissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MissionScalarFieldEnum | Prisma.MissionScalarFieldEnum[]
}

/**
 * Property.inventories
 */
export type Property$inventoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inventory
   */
  select?: Prisma.InventorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inventory
   */
  omit?: Prisma.InventoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InventoryInclude<ExtArgs> | null
  where?: Prisma.InventoryWhereInput
  orderBy?: Prisma.InventoryOrderByWithRelationInput | Prisma.InventoryOrderByWithRelationInput[]
  cursor?: Prisma.InventoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InventoryScalarFieldEnum | Prisma.InventoryScalarFieldEnum[]
}

/**
 * Property without action
 */
export type PropertyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
}
