
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Property: 'Property',
  Lease: 'Lease',
  Inventory: 'Inventory',
  InventoryItem: 'InventoryItem',
  SignatureProof: 'SignatureProof',
  Payment: 'Payment',
  Transaction: 'Transaction',
  Mission: 'Mission',
  Incident: 'Incident',
  Lead: 'Lead'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  phone: 'phone',
  name: 'name',
  password: 'password',
  role: 'role',
  kycStatus: 'kycStatus',
  kycDocuments: 'kycDocuments',
  walletBalance: 'walletBalance',
  escrowBalance: 'escrowBalance',
  referralBalance: 'referralBalance',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const PropertyScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  address: 'address',
  commune: 'commune',
  price: 'price',
  type: 'type',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  surface: 'surface',
  images: 'images',
  isPublished: 'isPublished',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ownerId: 'ownerId'
} as const

export type PropertyScalarFieldEnum = (typeof PropertyScalarFieldEnum)[keyof typeof PropertyScalarFieldEnum]


export const LeaseScalarFieldEnum = {
  id: 'id',
  startDate: 'startDate',
  endDate: 'endDate',
  monthlyRent: 'monthlyRent',
  depositAmount: 'depositAmount',
  status: 'status',
  isActive: 'isActive',
  contractUrl: 'contractUrl',
  documentHash: 'documentHash',
  signatureStatus: 'signatureStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tenantId: 'tenantId',
  propertyId: 'propertyId'
} as const

export type LeaseScalarFieldEnum = (typeof LeaseScalarFieldEnum)[keyof typeof LeaseScalarFieldEnum]


export const InventoryScalarFieldEnum = {
  id: 'id',
  date: 'date',
  type: 'type',
  notes: 'notes',
  reportUrl: 'reportUrl',
  leaseId: 'leaseId',
  propertyId: 'propertyId',
  agentId: 'agentId'
} as const

export type InventoryScalarFieldEnum = (typeof InventoryScalarFieldEnum)[keyof typeof InventoryScalarFieldEnum]


export const InventoryItemScalarFieldEnum = {
  id: 'id',
  roomName: 'roomName',
  element: 'element',
  condition: 'condition',
  comment: 'comment',
  photos: 'photos',
  inventoryId: 'inventoryId'
} as const

export type InventoryItemScalarFieldEnum = (typeof InventoryItemScalarFieldEnum)[keyof typeof InventoryItemScalarFieldEnum]


export const SignatureProofScalarFieldEnum = {
  id: 'id',
  ipAddress: 'ipAddress',
  signedAt: 'signedAt',
  userAgent: 'userAgent',
  otpToken: 'otpToken',
  leaseId: 'leaseId',
  signerId: 'signerId'
} as const

export type SignatureProofScalarFieldEnum = (typeof SignatureProofScalarFieldEnum)[keyof typeof SignatureProofScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  date: 'date',
  type: 'type',
  status: 'status',
  method: 'method',
  reference: 'reference',
  amountOwner: 'amountOwner',
  amountPlatform: 'amountPlatform',
  amountAgent: 'amountAgent',
  leaseId: 'leaseId'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const TransactionScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  type: 'type',
  reason: 'reason',
  createdAt: 'createdAt',
  userId: 'userId'
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]


export const MissionScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  fee: 'fee',
  dateScheduled: 'dateScheduled',
  reportData: 'reportData',
  createdAt: 'createdAt',
  propertyId: 'propertyId',
  agentId: 'agentId'
} as const

export type MissionScalarFieldEnum = (typeof MissionScalarFieldEnum)[keyof typeof MissionScalarFieldEnum]


export const IncidentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  priority: 'priority',
  photos: 'photos',
  status: 'status',
  quoteAmount: 'quoteAmount',
  finalCost: 'finalCost',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  reporterId: 'reporterId',
  assignedToId: 'assignedToId',
  propertyId: 'propertyId'
} as const

export type IncidentScalarFieldEnum = (typeof IncidentScalarFieldEnum)[keyof typeof IncidentScalarFieldEnum]


export const LeadScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phone: 'phone',
  needs: 'needs',
  budget: 'budget',
  status: 'status',
  createdAt: 'createdAt',
  agentId: 'agentId'
} as const

export type LeadScalarFieldEnum = (typeof LeadScalarFieldEnum)[keyof typeof LeadScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

