
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Lease` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Lease
 * 
 */
export type LeaseModel = runtime.Types.Result.DefaultSelection<Prisma.$LeasePayload>

export type AggregateLease = {
  _count: LeaseCountAggregateOutputType | null
  _avg: LeaseAvgAggregateOutputType | null
  _sum: LeaseSumAggregateOutputType | null
  _min: LeaseMinAggregateOutputType | null
  _max: LeaseMaxAggregateOutputType | null
}

export type LeaseAvgAggregateOutputType = {
  monthlyRent: number | null
  depositAmount: number | null
}

export type LeaseSumAggregateOutputType = {
  monthlyRent: number | null
  depositAmount: number | null
}

export type LeaseMinAggregateOutputType = {
  id: string | null
  startDate: Date | null
  endDate: Date | null
  monthlyRent: number | null
  depositAmount: number | null
  status: $Enums.LeaseStatus | null
  isActive: boolean | null
  contractUrl: string | null
  documentHash: string | null
  signatureStatus: $Enums.SignatureStatus | null
  createdAt: Date | null
  updatedAt: Date | null
  tenantId: string | null
  propertyId: string | null
}

export type LeaseMaxAggregateOutputType = {
  id: string | null
  startDate: Date | null
  endDate: Date | null
  monthlyRent: number | null
  depositAmount: number | null
  status: $Enums.LeaseStatus | null
  isActive: boolean | null
  contractUrl: string | null
  documentHash: string | null
  signatureStatus: $Enums.SignatureStatus | null
  createdAt: Date | null
  updatedAt: Date | null
  tenantId: string | null
  propertyId: string | null
}

export type LeaseCountAggregateOutputType = {
  id: number
  startDate: number
  endDate: number
  monthlyRent: number
  depositAmount: number
  status: number
  isActive: number
  contractUrl: number
  documentHash: number
  signatureStatus: number
  createdAt: number
  updatedAt: number
  tenantId: number
  propertyId: number
  _all: number
}


export type LeaseAvgAggregateInputType = {
  monthlyRent?: true
  depositAmount?: true
}

export type LeaseSumAggregateInputType = {
  monthlyRent?: true
  depositAmount?: true
}

export type LeaseMinAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  monthlyRent?: true
  depositAmount?: true
  status?: true
  isActive?: true
  contractUrl?: true
  documentHash?: true
  signatureStatus?: true
  createdAt?: true
  updatedAt?: true
  tenantId?: true
  propertyId?: true
}

export type LeaseMaxAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  monthlyRent?: true
  depositAmount?: true
  status?: true
  isActive?: true
  contractUrl?: true
  documentHash?: true
  signatureStatus?: true
  createdAt?: true
  updatedAt?: true
  tenantId?: true
  propertyId?: true
}

export type LeaseCountAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  monthlyRent?: true
  depositAmount?: true
  status?: true
  isActive?: true
  contractUrl?: true
  documentHash?: true
  signatureStatus?: true
  createdAt?: true
  updatedAt?: true
  tenantId?: true
  propertyId?: true
  _all?: true
}

export type LeaseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lease to aggregate.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Leases
  **/
  _count?: true | LeaseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LeaseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LeaseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeaseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeaseMaxAggregateInputType
}

export type GetLeaseAggregateType<T extends LeaseAggregateArgs> = {
      [P in keyof T & keyof AggregateLease]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLease[P]>
    : Prisma.GetScalarType<T[P], AggregateLease[P]>
}




export type LeaseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeaseWhereInput
  orderBy?: Prisma.LeaseOrderByWithAggregationInput | Prisma.LeaseOrderByWithAggregationInput[]
  by: Prisma.LeaseScalarFieldEnum[] | Prisma.LeaseScalarFieldEnum
  having?: Prisma.LeaseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeaseCountAggregateInputType | true
  _avg?: LeaseAvgAggregateInputType
  _sum?: LeaseSumAggregateInputType
  _min?: LeaseMinAggregateInputType
  _max?: LeaseMaxAggregateInputType
}

export type LeaseGroupByOutputType = {
  id: string
  startDate: Date
  endDate: Date | null
  monthlyRent: number
  depositAmount: number
  status: $Enums.LeaseStatus
  isActive: boolean
  contractUrl: string | null
  documentHash: string | null
  signatureStatus: $Enums.SignatureStatus
  createdAt: Date
  updatedAt: Date
  tenantId: string
  propertyId: string
  _count: LeaseCountAggregateOutputType | null
  _avg: LeaseAvgAggregateOutputType | null
  _sum: LeaseSumAggregateOutputType | null
  _min: LeaseMinAggregateOutputType | null
  _max: LeaseMaxAggregateOutputType | null
}

type GetLeaseGroupByPayload<T extends LeaseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeaseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeaseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeaseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeaseGroupByOutputType[P]>
      }
    >
  >



export type LeaseWhereInput = {
  AND?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  OR?: Prisma.LeaseWhereInput[]
  NOT?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  id?: Prisma.StringFilter<"Lease"> | string
  startDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeNullableFilter<"Lease"> | Date | string | null
  monthlyRent?: Prisma.IntFilter<"Lease"> | number
  depositAmount?: Prisma.IntFilter<"Lease"> | number
  status?: Prisma.EnumLeaseStatusFilter<"Lease"> | $Enums.LeaseStatus
  isActive?: Prisma.BoolFilter<"Lease"> | boolean
  contractUrl?: Prisma.StringNullableFilter<"Lease"> | string | null
  documentHash?: Prisma.StringNullableFilter<"Lease"> | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFilter<"Lease"> | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFilter<"Lease"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Lease"> | Date | string
  tenantId?: Prisma.StringFilter<"Lease"> | string
  propertyId?: Prisma.StringFilter<"Lease"> | string
  tenant?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  payments?: Prisma.PaymentListRelationFilter
  signatures?: Prisma.SignatureProofListRelationFilter
  inventories?: Prisma.InventoryListRelationFilter
}

export type LeaseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  contractUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  documentHash?: Prisma.SortOrderInput | Prisma.SortOrder
  signatureStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  tenant?: Prisma.UserOrderByWithRelationInput
  property?: Prisma.PropertyOrderByWithRelationInput
  payments?: Prisma.PaymentOrderByRelationAggregateInput
  signatures?: Prisma.SignatureProofOrderByRelationAggregateInput
  inventories?: Prisma.InventoryOrderByRelationAggregateInput
}

export type LeaseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  OR?: Prisma.LeaseWhereInput[]
  NOT?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  startDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeNullableFilter<"Lease"> | Date | string | null
  monthlyRent?: Prisma.IntFilter<"Lease"> | number
  depositAmount?: Prisma.IntFilter<"Lease"> | number
  status?: Prisma.EnumLeaseStatusFilter<"Lease"> | $Enums.LeaseStatus
  isActive?: Prisma.BoolFilter<"Lease"> | boolean
  contractUrl?: Prisma.StringNullableFilter<"Lease"> | string | null
  documentHash?: Prisma.StringNullableFilter<"Lease"> | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFilter<"Lease"> | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFilter<"Lease"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Lease"> | Date | string
  tenantId?: Prisma.StringFilter<"Lease"> | string
  propertyId?: Prisma.StringFilter<"Lease"> | string
  tenant?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  payments?: Prisma.PaymentListRelationFilter
  signatures?: Prisma.SignatureProofListRelationFilter
  inventories?: Prisma.InventoryListRelationFilter
}, "id">

export type LeaseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  contractUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  documentHash?: Prisma.SortOrderInput | Prisma.SortOrder
  signatureStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  _count?: Prisma.LeaseCountOrderByAggregateInput
  _avg?: Prisma.LeaseAvgOrderByAggregateInput
  _max?: Prisma.LeaseMaxOrderByAggregateInput
  _min?: Prisma.LeaseMinOrderByAggregateInput
  _sum?: Prisma.LeaseSumOrderByAggregateInput
}

export type LeaseScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeaseScalarWhereWithAggregatesInput | Prisma.LeaseScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeaseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeaseScalarWhereWithAggregatesInput | Prisma.LeaseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Lease"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Lease"> | Date | string | null
  monthlyRent?: Prisma.IntWithAggregatesFilter<"Lease"> | number
  depositAmount?: Prisma.IntWithAggregatesFilter<"Lease"> | number
  status?: Prisma.EnumLeaseStatusWithAggregatesFilter<"Lease"> | $Enums.LeaseStatus
  isActive?: Prisma.BoolWithAggregatesFilter<"Lease"> | boolean
  contractUrl?: Prisma.StringNullableWithAggregatesFilter<"Lease"> | string | null
  documentHash?: Prisma.StringNullableWithAggregatesFilter<"Lease"> | string | null
  signatureStatus?: Prisma.EnumSignatureStatusWithAggregatesFilter<"Lease"> | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Lease"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Lease"> | Date | string
  tenantId?: Prisma.StringWithAggregatesFilter<"Lease"> | string
  propertyId?: Prisma.StringWithAggregatesFilter<"Lease"> | string
}

export type LeaseCreateInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenant: Prisma.UserCreateNestedOneWithoutLeasesInput
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
  propertyId: string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofUncheckedCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.UserUpdateOneRequiredWithoutLeasesNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUncheckedUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseCreateManyInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
  propertyId: string
}

export type LeaseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LeaseListRelationFilter = {
  every?: Prisma.LeaseWhereInput
  some?: Prisma.LeaseWhereInput
  none?: Prisma.LeaseWhereInput
}

export type LeaseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeaseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  contractUrl?: Prisma.SortOrder
  documentHash?: Prisma.SortOrder
  signatureStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type LeaseAvgOrderByAggregateInput = {
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
}

export type LeaseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  contractUrl?: Prisma.SortOrder
  documentHash?: Prisma.SortOrder
  signatureStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type LeaseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  contractUrl?: Prisma.SortOrder
  documentHash?: Prisma.SortOrder
  signatureStatus?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type LeaseSumOrderByAggregateInput = {
  monthlyRent?: Prisma.SortOrder
  depositAmount?: Prisma.SortOrder
}

export type LeaseScalarRelationFilter = {
  is?: Prisma.LeaseWhereInput
  isNot?: Prisma.LeaseWhereInput
}

export type LeaseCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUncheckedCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutTenantInput | Prisma.LeaseUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseUncheckedUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutTenantInput | Prisma.LeaseUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUncheckedCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput | Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseUncheckedUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput | Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumLeaseStatusFieldUpdateOperationsInput = {
  set?: $Enums.LeaseStatus
}

export type EnumSignatureStatusFieldUpdateOperationsInput = {
  set?: $Enums.SignatureStatus
}

export type LeaseCreateNestedOneWithoutInventoriesInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutInventoriesInput, Prisma.LeaseUncheckedCreateWithoutInventoriesInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutInventoriesInput
  connect?: Prisma.LeaseWhereUniqueInput
}

export type LeaseUpdateOneRequiredWithoutInventoriesNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutInventoriesInput, Prisma.LeaseUncheckedCreateWithoutInventoriesInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutInventoriesInput
  upsert?: Prisma.LeaseUpsertWithoutInventoriesInput
  connect?: Prisma.LeaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseUpdateToOneWithWhereWithoutInventoriesInput, Prisma.LeaseUpdateWithoutInventoriesInput>, Prisma.LeaseUncheckedUpdateWithoutInventoriesInput>
}

export type LeaseCreateNestedOneWithoutSignaturesInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutSignaturesInput, Prisma.LeaseUncheckedCreateWithoutSignaturesInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutSignaturesInput
  connect?: Prisma.LeaseWhereUniqueInput
}

export type LeaseUpdateOneRequiredWithoutSignaturesNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutSignaturesInput, Prisma.LeaseUncheckedCreateWithoutSignaturesInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutSignaturesInput
  upsert?: Prisma.LeaseUpsertWithoutSignaturesInput
  connect?: Prisma.LeaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseUpdateToOneWithWhereWithoutSignaturesInput, Prisma.LeaseUpdateWithoutSignaturesInput>, Prisma.LeaseUncheckedUpdateWithoutSignaturesInput>
}

export type LeaseCreateNestedOneWithoutPaymentsInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPaymentsInput
  connect?: Prisma.LeaseWhereUniqueInput
}

export type LeaseUpdateOneRequiredWithoutPaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPaymentsInput
  upsert?: Prisma.LeaseUpsertWithoutPaymentsInput
  connect?: Prisma.LeaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseUpdateToOneWithWhereWithoutPaymentsInput, Prisma.LeaseUpdateWithoutPaymentsInput>, Prisma.LeaseUncheckedUpdateWithoutPaymentsInput>
}

export type LeaseCreateWithoutTenantInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutTenantInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  propertyId: string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofUncheckedCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutTenantInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput>
}

export type LeaseCreateManyTenantInputEnvelope = {
  data: Prisma.LeaseCreateManyTenantInput | Prisma.LeaseCreateManyTenantInput[]
  skipDuplicates?: boolean
}

export type LeaseUpsertWithWhereUniqueWithoutTenantInput = {
  where: Prisma.LeaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutTenantInput, Prisma.LeaseUncheckedUpdateWithoutTenantInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput>
}

export type LeaseUpdateWithWhereUniqueWithoutTenantInput = {
  where: Prisma.LeaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutTenantInput, Prisma.LeaseUncheckedUpdateWithoutTenantInput>
}

export type LeaseUpdateManyWithWhereWithoutTenantInput = {
  where: Prisma.LeaseScalarWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyWithoutTenantInput>
}

export type LeaseScalarWhereInput = {
  AND?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
  OR?: Prisma.LeaseScalarWhereInput[]
  NOT?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
  id?: Prisma.StringFilter<"Lease"> | string
  startDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeNullableFilter<"Lease"> | Date | string | null
  monthlyRent?: Prisma.IntFilter<"Lease"> | number
  depositAmount?: Prisma.IntFilter<"Lease"> | number
  status?: Prisma.EnumLeaseStatusFilter<"Lease"> | $Enums.LeaseStatus
  isActive?: Prisma.BoolFilter<"Lease"> | boolean
  contractUrl?: Prisma.StringNullableFilter<"Lease"> | string | null
  documentHash?: Prisma.StringNullableFilter<"Lease"> | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFilter<"Lease"> | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFilter<"Lease"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Lease"> | Date | string
  tenantId?: Prisma.StringFilter<"Lease"> | string
  propertyId?: Prisma.StringFilter<"Lease"> | string
}

export type LeaseCreateWithoutPropertyInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenant: Prisma.UserCreateNestedOneWithoutLeasesInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutPropertyInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofUncheckedCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutPropertyInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput>
}

export type LeaseCreateManyPropertyInputEnvelope = {
  data: Prisma.LeaseCreateManyPropertyInput | Prisma.LeaseCreateManyPropertyInput[]
  skipDuplicates?: boolean
}

export type LeaseUpsertWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.LeaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutPropertyInput, Prisma.LeaseUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput>
}

export type LeaseUpdateWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.LeaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutPropertyInput, Prisma.LeaseUncheckedUpdateWithoutPropertyInput>
}

export type LeaseUpdateManyWithWhereWithoutPropertyInput = {
  where: Prisma.LeaseScalarWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyWithoutPropertyInput>
}

export type LeaseCreateWithoutInventoriesInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenant: Prisma.UserCreateNestedOneWithoutLeasesInput
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutInventoriesInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
  propertyId: string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
  signatures?: Prisma.SignatureProofUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutInventoriesInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutInventoriesInput, Prisma.LeaseUncheckedCreateWithoutInventoriesInput>
}

export type LeaseUpsertWithoutInventoriesInput = {
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutInventoriesInput, Prisma.LeaseUncheckedUpdateWithoutInventoriesInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutInventoriesInput, Prisma.LeaseUncheckedCreateWithoutInventoriesInput>
  where?: Prisma.LeaseWhereInput
}

export type LeaseUpdateToOneWithWhereWithoutInventoriesInput = {
  where?: Prisma.LeaseWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutInventoriesInput, Prisma.LeaseUncheckedUpdateWithoutInventoriesInput>
}

export type LeaseUpdateWithoutInventoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.UserUpdateOneRequiredWithoutLeasesNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutInventoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseCreateWithoutSignaturesInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenant: Prisma.UserCreateNestedOneWithoutLeasesInput
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutSignaturesInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
  propertyId: string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutSignaturesInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutSignaturesInput, Prisma.LeaseUncheckedCreateWithoutSignaturesInput>
}

export type LeaseUpsertWithoutSignaturesInput = {
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutSignaturesInput, Prisma.LeaseUncheckedUpdateWithoutSignaturesInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutSignaturesInput, Prisma.LeaseUncheckedCreateWithoutSignaturesInput>
  where?: Prisma.LeaseWhereInput
}

export type LeaseUpdateToOneWithWhereWithoutSignaturesInput = {
  where?: Prisma.LeaseWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutSignaturesInput, Prisma.LeaseUncheckedUpdateWithoutSignaturesInput>
}

export type LeaseUpdateWithoutSignaturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.UserUpdateOneRequiredWithoutLeasesNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutSignaturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseCreateWithoutPaymentsInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenant: Prisma.UserCreateNestedOneWithoutLeasesInput
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  signatures?: Prisma.SignatureProofCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutPaymentsInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
  propertyId: string
  signatures?: Prisma.SignatureProofUncheckedCreateNestedManyWithoutLeaseInput
  inventories?: Prisma.InventoryUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutPaymentsInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
}

export type LeaseUpsertWithoutPaymentsInput = {
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutPaymentsInput, Prisma.LeaseUncheckedUpdateWithoutPaymentsInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
  where?: Prisma.LeaseWhereInput
}

export type LeaseUpdateToOneWithWhereWithoutPaymentsInput = {
  where?: Prisma.LeaseWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutPaymentsInput, Prisma.LeaseUncheckedUpdateWithoutPaymentsInput>
}

export type LeaseUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.UserUpdateOneRequiredWithoutLeasesNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  signatures?: Prisma.SignatureProofUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  signatures?: Prisma.SignatureProofUncheckedUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseCreateManyTenantInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  propertyId: string
}

export type LeaseUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUncheckedUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateManyWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  propertyId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LeaseCreateManyPropertyInput = {
  id?: string
  startDate: Date | string
  endDate?: Date | string | null
  monthlyRent: number
  depositAmount: number
  status?: $Enums.LeaseStatus
  isActive?: boolean
  contractUrl?: string | null
  documentHash?: string | null
  signatureStatus?: $Enums.SignatureStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  tenantId: string
}

export type LeaseUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.UserUpdateOneRequiredWithoutLeasesNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
  signatures?: Prisma.SignatureProofUncheckedUpdateManyWithoutLeaseNestedInput
  inventories?: Prisma.InventoryUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateManyWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  monthlyRent?: Prisma.IntFieldUpdateOperationsInput | number
  depositAmount?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumLeaseStatusFieldUpdateOperationsInput | $Enums.LeaseStatus
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  contractUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documentHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signatureStatus?: Prisma.EnumSignatureStatusFieldUpdateOperationsInput | $Enums.SignatureStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type LeaseCountOutputType
 */

export type LeaseCountOutputType = {
  payments: number
  signatures: number
  inventories: number
}

export type LeaseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payments?: boolean | LeaseCountOutputTypeCountPaymentsArgs
  signatures?: boolean | LeaseCountOutputTypeCountSignaturesArgs
  inventories?: boolean | LeaseCountOutputTypeCountInventoriesArgs
}

/**
 * LeaseCountOutputType without action
 */
export type LeaseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCountOutputType
   */
  select?: Prisma.LeaseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LeaseCountOutputType without action
 */
export type LeaseCountOutputTypeCountPaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentWhereInput
}

/**
 * LeaseCountOutputType without action
 */
export type LeaseCountOutputTypeCountSignaturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SignatureProofWhereInput
}

/**
 * LeaseCountOutputType without action
 */
export type LeaseCountOutputTypeCountInventoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InventoryWhereInput
}


export type LeaseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  monthlyRent?: boolean
  depositAmount?: boolean
  status?: boolean
  isActive?: boolean
  contractUrl?: boolean
  documentHash?: boolean
  signatureStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tenantId?: boolean
  propertyId?: boolean
  tenant?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  payments?: boolean | Prisma.Lease$paymentsArgs<ExtArgs>
  signatures?: boolean | Prisma.Lease$signaturesArgs<ExtArgs>
  inventories?: boolean | Prisma.Lease$inventoriesArgs<ExtArgs>
  _count?: boolean | Prisma.LeaseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lease"]>

export type LeaseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  monthlyRent?: boolean
  depositAmount?: boolean
  status?: boolean
  isActive?: boolean
  contractUrl?: boolean
  documentHash?: boolean
  signatureStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tenantId?: boolean
  propertyId?: boolean
  tenant?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lease"]>

export type LeaseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  monthlyRent?: boolean
  depositAmount?: boolean
  status?: boolean
  isActive?: boolean
  contractUrl?: boolean
  documentHash?: boolean
  signatureStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tenantId?: boolean
  propertyId?: boolean
  tenant?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lease"]>

export type LeaseSelectScalar = {
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  monthlyRent?: boolean
  depositAmount?: boolean
  status?: boolean
  isActive?: boolean
  contractUrl?: boolean
  documentHash?: boolean
  signatureStatus?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tenantId?: boolean
  propertyId?: boolean
}

export type LeaseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "startDate" | "endDate" | "monthlyRent" | "depositAmount" | "status" | "isActive" | "contractUrl" | "documentHash" | "signatureStatus" | "createdAt" | "updatedAt" | "tenantId" | "propertyId", ExtArgs["result"]["lease"]>
export type LeaseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  payments?: boolean | Prisma.Lease$paymentsArgs<ExtArgs>
  signatures?: boolean | Prisma.Lease$signaturesArgs<ExtArgs>
  inventories?: boolean | Prisma.Lease$inventoriesArgs<ExtArgs>
  _count?: boolean | Prisma.LeaseCountOutputTypeDefaultArgs<ExtArgs>
}
export type LeaseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}
export type LeaseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}

export type $LeasePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Lease"
  objects: {
    tenant: Prisma.$UserPayload<ExtArgs>
    property: Prisma.$PropertyPayload<ExtArgs>
    payments: Prisma.$PaymentPayload<ExtArgs>[]
    signatures: Prisma.$SignatureProofPayload<ExtArgs>[]
    inventories: Prisma.$InventoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    startDate: Date
    endDate: Date | null
    monthlyRent: number
    depositAmount: number
    status: $Enums.LeaseStatus
    isActive: boolean
    contractUrl: string | null
    documentHash: string | null
    signatureStatus: $Enums.SignatureStatus
    createdAt: Date
    updatedAt: Date
    tenantId: string
    propertyId: string
  }, ExtArgs["result"]["lease"]>
  composites: {}
}

export type LeaseGetPayload<S extends boolean | null | undefined | LeaseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeasePayload, S>

export type LeaseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeaseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeaseCountAggregateInputType | true
  }

export interface LeaseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Lease'], meta: { name: 'Lease' } }
  /**
   * Find zero or one Lease that matches the filter.
   * @param {LeaseFindUniqueArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeaseFindUniqueArgs>(args: Prisma.SelectSubset<T, LeaseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lease that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeaseFindUniqueOrThrowArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeaseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeaseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lease that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseFindFirstArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeaseFindFirstArgs>(args?: Prisma.SelectSubset<T, LeaseFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lease that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseFindFirstOrThrowArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeaseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeaseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Leases that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Leases
   * const leases = await prisma.lease.findMany()
   * 
   * // Get first 10 Leases
   * const leases = await prisma.lease.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const leaseWithIdOnly = await prisma.lease.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LeaseFindManyArgs>(args?: Prisma.SelectSubset<T, LeaseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lease.
   * @param {LeaseCreateArgs} args - Arguments to create a Lease.
   * @example
   * // Create one Lease
   * const Lease = await prisma.lease.create({
   *   data: {
   *     // ... data to create a Lease
   *   }
   * })
   * 
   */
  create<T extends LeaseCreateArgs>(args: Prisma.SelectSubset<T, LeaseCreateArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Leases.
   * @param {LeaseCreateManyArgs} args - Arguments to create many Leases.
   * @example
   * // Create many Leases
   * const lease = await prisma.lease.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeaseCreateManyArgs>(args?: Prisma.SelectSubset<T, LeaseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Leases and returns the data saved in the database.
   * @param {LeaseCreateManyAndReturnArgs} args - Arguments to create many Leases.
   * @example
   * // Create many Leases
   * const lease = await prisma.lease.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Leases and only return the `id`
   * const leaseWithIdOnly = await prisma.lease.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeaseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeaseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Lease.
   * @param {LeaseDeleteArgs} args - Arguments to delete one Lease.
   * @example
   * // Delete one Lease
   * const Lease = await prisma.lease.delete({
   *   where: {
   *     // ... filter to delete one Lease
   *   }
   * })
   * 
   */
  delete<T extends LeaseDeleteArgs>(args: Prisma.SelectSubset<T, LeaseDeleteArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lease.
   * @param {LeaseUpdateArgs} args - Arguments to update one Lease.
   * @example
   * // Update one Lease
   * const lease = await prisma.lease.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeaseUpdateArgs>(args: Prisma.SelectSubset<T, LeaseUpdateArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Leases.
   * @param {LeaseDeleteManyArgs} args - Arguments to filter Leases to delete.
   * @example
   * // Delete a few Leases
   * const { count } = await prisma.lease.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeaseDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeaseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Leases
   * const lease = await prisma.lease.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeaseUpdateManyArgs>(args: Prisma.SelectSubset<T, LeaseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leases and returns the data updated in the database.
   * @param {LeaseUpdateManyAndReturnArgs} args - Arguments to update many Leases.
   * @example
   * // Update many Leases
   * const lease = await prisma.lease.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Leases and only return the `id`
   * const leaseWithIdOnly = await prisma.lease.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeaseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeaseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Lease.
   * @param {LeaseUpsertArgs} args - Arguments to update or create a Lease.
   * @example
   * // Update or create a Lease
   * const lease = await prisma.lease.upsert({
   *   create: {
   *     // ... data to create a Lease
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lease we want to update
   *   }
   * })
   */
  upsert<T extends LeaseUpsertArgs>(args: Prisma.SelectSubset<T, LeaseUpsertArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Leases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCountArgs} args - Arguments to filter Leases to count.
   * @example
   * // Count the number of Leases
   * const count = await prisma.lease.count({
   *   where: {
   *     // ... the filter for the Leases we want to count
   *   }
   * })
  **/
  count<T extends LeaseCountArgs>(
    args?: Prisma.Subset<T, LeaseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeaseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lease.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeaseAggregateArgs>(args: Prisma.Subset<T, LeaseAggregateArgs>): Prisma.PrismaPromise<GetLeaseAggregateType<T>>

  /**
   * Group by Lease.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeaseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeaseGroupByArgs['orderBy'] }
      : { orderBy?: LeaseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeaseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeaseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Lease model
 */
readonly fields: LeaseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Lease.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeaseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tenant<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  property<T extends Prisma.PropertyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PropertyDefaultArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  payments<T extends Prisma.Lease$paymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lease$paymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  signatures<T extends Prisma.Lease$signaturesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lease$signaturesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignatureProofPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  inventories<T extends Prisma.Lease$inventoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lease$inventoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InventoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Lease model
 */
export interface LeaseFieldRefs {
  readonly id: Prisma.FieldRef<"Lease", 'String'>
  readonly startDate: Prisma.FieldRef<"Lease", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"Lease", 'DateTime'>
  readonly monthlyRent: Prisma.FieldRef<"Lease", 'Int'>
  readonly depositAmount: Prisma.FieldRef<"Lease", 'Int'>
  readonly status: Prisma.FieldRef<"Lease", 'LeaseStatus'>
  readonly isActive: Prisma.FieldRef<"Lease", 'Boolean'>
  readonly contractUrl: Prisma.FieldRef<"Lease", 'String'>
  readonly documentHash: Prisma.FieldRef<"Lease", 'String'>
  readonly signatureStatus: Prisma.FieldRef<"Lease", 'SignatureStatus'>
  readonly createdAt: Prisma.FieldRef<"Lease", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Lease", 'DateTime'>
  readonly tenantId: Prisma.FieldRef<"Lease", 'String'>
  readonly propertyId: Prisma.FieldRef<"Lease", 'String'>
}
    

// Custom InputTypes
/**
 * Lease findUnique
 */
export type LeaseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease findUniqueOrThrow
 */
export type LeaseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease findFirst
 */
export type LeaseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leases.
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leases.
   */
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Lease findFirstOrThrow
 */
export type LeaseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leases.
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leases.
   */
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Lease findMany
 */
export type LeaseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Leases to fetch.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Leases.
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Lease create
 */
export type LeaseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * The data needed to create a Lease.
   */
  data: Prisma.XOR<Prisma.LeaseCreateInput, Prisma.LeaseUncheckedCreateInput>
}

/**
 * Lease createMany
 */
export type LeaseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Leases.
   */
  data: Prisma.LeaseCreateManyInput | Prisma.LeaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lease createManyAndReturn
 */
export type LeaseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * The data used to create many Leases.
   */
  data: Prisma.LeaseCreateManyInput | Prisma.LeaseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Lease update
 */
export type LeaseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * The data needed to update a Lease.
   */
  data: Prisma.XOR<Prisma.LeaseUpdateInput, Prisma.LeaseUncheckedUpdateInput>
  /**
   * Choose, which Lease to update.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease updateMany
 */
export type LeaseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Leases.
   */
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyInput>
  /**
   * Filter which Leases to update
   */
  where?: Prisma.LeaseWhereInput
  /**
   * Limit how many Leases to update.
   */
  limit?: number
}

/**
 * Lease updateManyAndReturn
 */
export type LeaseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * The data used to update Leases.
   */
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyInput>
  /**
   * Filter which Leases to update
   */
  where?: Prisma.LeaseWhereInput
  /**
   * Limit how many Leases to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Lease upsert
 */
export type LeaseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * The filter to search for the Lease to update in case it exists.
   */
  where: Prisma.LeaseWhereUniqueInput
  /**
   * In case the Lease found by the `where` argument doesn't exist, create a new Lease with this data.
   */
  create: Prisma.XOR<Prisma.LeaseCreateInput, Prisma.LeaseUncheckedCreateInput>
  /**
   * In case the Lease was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeaseUpdateInput, Prisma.LeaseUncheckedUpdateInput>
}

/**
 * Lease delete
 */
export type LeaseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter which Lease to delete.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease deleteMany
 */
export type LeaseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Leases to delete
   */
  where?: Prisma.LeaseWhereInput
  /**
   * Limit how many Leases to delete.
   */
  limit?: number
}

/**
 * Lease.payments
 */
export type Lease$paymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Payment
   */
  select?: Prisma.PaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Payment
   */
  omit?: Prisma.PaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentInclude<ExtArgs> | null
  where?: Prisma.PaymentWhereInput
  orderBy?: Prisma.PaymentOrderByWithRelationInput | Prisma.PaymentOrderByWithRelationInput[]
  cursor?: Prisma.PaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentScalarFieldEnum | Prisma.PaymentScalarFieldEnum[]
}

/**
 * Lease.signatures
 */
export type Lease$signaturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignatureProof
   */
  select?: Prisma.SignatureProofSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignatureProof
   */
  omit?: Prisma.SignatureProofOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SignatureProofInclude<ExtArgs> | null
  where?: Prisma.SignatureProofWhereInput
  orderBy?: Prisma.SignatureProofOrderByWithRelationInput | Prisma.SignatureProofOrderByWithRelationInput[]
  cursor?: Prisma.SignatureProofWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SignatureProofScalarFieldEnum | Prisma.SignatureProofScalarFieldEnum[]
}

/**
 * Lease.inventories
 */
export type Lease$inventoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Inventory
   */
  select?: Prisma.InventorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Inventory
   */
  omit?: Prisma.InventoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InventoryInclude<ExtArgs> | null
  where?: Prisma.InventoryWhereInput
  orderBy?: Prisma.InventoryOrderByWithRelationInput | Prisma.InventoryOrderByWithRelationInput[]
  cursor?: Prisma.InventoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InventoryScalarFieldEnum | Prisma.InventoryScalarFieldEnum[]
}

/**
 * Lease without action
 */
export type LeaseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
}
