-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "bathrooms" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "bedrooms" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "maxGuests" INTEGER NOT NULL DEFAULT 2;
