name: Babimmo CI/CD - Pipeline Qualité

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-logic-tests:
    name: 🧠 Logique Métier (Vitest)
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      # On configure Node et on lui dit de mettre en cache les modules npm pour accélérer les futurs tests
      - name: ⚙️ Configuration Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Plus besoin de l'action pnpm, npm est natif sur Node
      - name: 🏗️ Installation des dépendances
        run: npm install

      # Utilisation de npx (l'équivalent npm de pnpm dlx)
      - name: 🗄️ Génération du Client Prisma
        run: npx prisma generate

      # Lancement direct de vitest avec npx
      - name: 🧪 Exécution des tests Vitest
        run: npx vitest run
