name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # 1. CRÉATION DE LA BASE DE DONNÉES ÉPHÉMÈRE
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: babimmo_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci

    # 2. INITIALISATION DE LA BASE DE DONNÉES AVEC PRISMA
    - name: Générer le client Prisma et créer les tables
      env:
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/babimmo_test?schema=public"
        DIRECT_URL: "postgresql://postgres:password@localhost:5432/babimmo_test?schema=public"
      run: |
        npx prisma generate
        npx prisma db push --accept-data-loss

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    # 3. LANCEMENT DES TESTS E2E
    - name: Run Playwright tests
      run: npx playwright test
      env: 
        AUTH_SECRET: "une-cle-secrete-bidon-pour-les-tests-github-actions"
        NEXTAUTH_SECRET: "une-cle-secrete-bidon-pour-les-tests-github-actions"
        NEXTAUTH_URL: "http://localhost:3000"
        # On indique à Next.js de se connecter à notre base de données jetable
        DATABASE_URL: "postgresql://postgres:password@localhost:5432/babimmo_test?schema=public"
        DIRECT_URL: "postgresql://postgres:password@localhost:5432/babimmo_test?schema=public"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
